name: CI
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  Lint:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "16.x"

      - name: Commit lint ✨
        uses: wagoid/commitlint-github-action@v5

      - name: Install dependencies
        run: npm install

      - name: Format ✨
        run: npm run test.format

      - name: Lint ✨
        run: npm run test.lint

  Release:
    needs: [Lint]
    if: github.ref == 'refs/heads/master' &&
      github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "16.x"
      - name: NPM install
        run: npm install

      - name: Release 🎉
        uses: cycjimmy/semantic-release-action@v2
        with:
          extends: |
            @atom-ide-community/semantic-release-npm-config
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN  }}
